# Problem 2:
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

Fibonacci = [1, 2]
i=0
while True:
    Fibonacci_n = Fibonacci[i] + Fibonacci[i+1]
    Fibonacci.append(Fibonacci_n)
    i+=1
    if Fibonacci[-1] > 4000000:
        break
suma = 0
Fibonacci_par = []
for i in range(len(Fibonacci)):
    if Fibonacci[i] % 2 == 0:
        suma += Fibonacci[i]
        Fibonacci_par.append(Fibonacci[i])
print(suma)